import Head from "next/head";
import React from "react";
import { CatMaskPaths, CatPaths } from "@/assets/cat/paths";

import dynamic from "next/dynamic";
import styled from "styled-components";

const DrawWithin = dynamic(
  () => import("@heypano/pupds").then(({ DrawWithin }) => DrawWithin),
  { ssr: false }
); // Async API cannot be server-side rendered

const StMain = styled.main`
  height: 100%;
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StMain>
        <DrawWithin
          viewBox="0 0 202.53 230.74"
          ImagePaths={<CatPaths />}
          MaskPaths={<CatMaskPaths />}
        />
      </StMain>
    </>
  );
}
