import Head from "next/head";
import React, { useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";
import { CatMaskPaths, CatPaths } from "@/assets/cat/paths";
import styled from "styled-components";

const DrawWithin = dynamic(() => import("@/components/DrawWithin"), {
  ssr: false,
});

const StMain = styled.main`
  height: 100%;
`;
export default function Cat() {
  const ref = useRef<HTMLElement | null>(null);
  const exportMethodRef = useRef<
    ((element: HTMLElement, imageFileName: string) => Promise<void>) | null
  >(null);
  const exportMethod = exportMethodRef.current;
  useEffect(() => {
    import("@heypano/pupds").then(({ exportAsImage }) => {
      exportMethodRef.current = exportAsImage;
    });
  }, []);

  return (
    <>
      <Head>
        <title>Where to pet CATNAME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StMain>
        <button
          onClick={() => {
            if (ref.current) {
              exportMethod?.(ref.current, "wheretopet_CATNAME.png").then(() => {
                console.log("saved");
              });
            }
          }}
        >
          Save
        </button>
        <DrawWithin
          viewBox="0 0 202.53 230.74"
          ImagePaths={<CatPaths />}
          MaskPaths={<CatMaskPaths />}
          containerRef={ref}
        />
      </StMain>
    </>
  );
}
